### PR TITLE
Add support for snapshot to stdout

### PR DESCRIPTION
**Pull request by knauth**
tt-smi -s now sends JSON to stdout, -f writes it to a file, per issue #39 

Note that this isn't currently usable with pipes, e.g.  `tt-smi -s | jq` because the backend instantiation outputs a progress bar. Some of the progress bars appear to be in tt-tools-common? Making them transient isn't a fix since that relies on terminal control characters which don't properly affect piped output. Before making far-reaching changes I wanted to open discussion of how to resolve this issue.

### CODE REVIEW

**Comment by knauth** [comment]
Now that I'm looking at issue #57, it seems like the progress bars are causing issues elsewhere. I'm thinking they should not be default behavior? The long cold start times are frustrating but I would rather look into optimizing textual/our end than invite so many TTY issues.

**Comment by TTDRosen** [comment]
There should be some detection for you being in an interactive terminal? I don't know how well textual supports it, but when I write TUIs I usually try to detect pipes/redirects and not produce coloured or live output.

**Comment by knauth** [comment]
I'll take a look.

**Comment by knauth** [comment]
@TTDRosen Updated with new functionality and tt-tools-common bump. Plan is to merge and then resolve a couple more small issues to put all those changes under the 3.0.5 umbrella. Thoughts?

**Review by TTDRosen — APPROVED** [review]
lgtm!

**Pull request merged**
